######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 4 17:49:14 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += SnapTool.h
SOURCES += main.cpp SnapTool.cpp
QT += core gui network
