######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 1 11:41:17 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Connection.h ConnectionData.h SnapServer.h
FORMS += SnapServer.ui
SOURCES += Connection.cpp ConnectionData.cpp main.cpp SnapServer.cpp
QT += network gui
