######################################################################
# Automatically generated by qmake (2.01a) Sun Aug 1 03:15:31 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += AccessorApp.h Connection.h ConnectionData.h
FORMS += AccessorApp.ui AccessorView.ui NewConnectionDialog.ui
SOURCES += AccessorApp.cpp Connection.cpp ConnectionData.cpp main.cpp
QT += network gui

